#!/usr/bin/env bash
# Build a self-contained "standalone" bundle for one or more ported games.
#
#   tools/make_standalone.sh soulcalibur [outrun ...]
#
# A bundle is a directory containing the game binary, every non-system shared
# library it needs (including the dlopen'ed GPU plugin, which the runtime loads
# from the executable's own folder), and a launch.sh with that game's flags
# baked in — replicated from play.sh's per-game case entries.
#
# IMPORTANT — what a bundle is NOT:
#   * Game data is NOT copied. launch.sh points --game_data_root at this
#     suite's games/<name>/extracted directory, which must still exist.
#   * Bundles contain recompiled, copyrighted game code. They are for LOCAL
#     USE ONLY and must never be committed, uploaded, or redistributed.
#     The output directory is git-ignored; keep it that way.
#
# Output goes to $STANDALONE_DIR (default: ~/XBLA/standalone/<name>/).
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST_BASE="${STANDALONE_DIR:-$HOME/XBLA/standalone}"

if [ $# -lt 1 ]; then
  echo "Usage: tools/make_standalone.sh <game> [<game> ...]"
  echo "Bundles are written to $DEST_BASE/<game>/"
  exit 1
fi

make_bundle() {
  local NAME="$1"
  local G="$ROOT/games/$NAME"
  local BIN="$G/project/out/build/linux-amd64/Release/$NAME"
  local DEST="$DEST_BASE/$NAME"

  if [ ! -x "$BIN" ]; then
    echo "SKIP $NAME: no built binary at $BIN"
    return 1
  fi
  if [ ! -d "$G/extracted" ]; then
    echo "WARN $NAME: $G/extracted missing — bundle will not boot until game data is extracted"
  fi

  # SDK output dir: read from the game's CMake cache (same logic as play.sh).
  local SDK_SRC=""
  if [ -f "$G/project/out/build/linux-amd64/CMakeCache.txt" ]; then
    SDK_SRC="$(grep -E '^REXGLUE_SDK_SOURCE_DIR' "$G/project/out/build/linux-amd64/CMakeCache.txt" | cut -d= -f2- || true)"
  fi
  local SDK_OUT="${SDK_SRC:-$HOME/development/xenon-native/repos/rexglue-sdk}/out/linux-amd64/Release"
  if [ ! -d "$SDK_OUT" ]; then
    echo "SKIP $NAME: SDK output dir not found: $SDK_OUT"
    return 1
  fi

  mkdir -p "$DEST"
  cp -f "$BIN" "$DEST/$NAME"

  # 1) Every SDK-built shared library. The GPU plugin librexgpu-xenos.so is
  #    dlopen'ed from the executable's folder (it never appears in ldd), and
  #    its own private deps (SPIRV-Tools, Tracy) may be dlopen'ed too — so
  #    take them all; there are only a handful.
  cp -f "$SDK_OUT"/*.so "$DEST/" 2>/dev/null || true

  # 2) Anything else ldd resolves from outside the system library dirs.
  local missing=0
  while read -r lib path; do
    case "$path" in
      /usr/lib*|/lib*|"") ;;                       # system-provided: don't bundle
      *) cp -f "$path" "$DEST/" ;;
    esac
  done < <(LD_LIBRARY_PATH="$SDK_OUT" ldd "$BIN" | awk '/=>/ {print $1, $3}')
  if LD_LIBRARY_PATH="$SDK_OUT" ldd "$BIN" | grep -q 'not found'; then
    echo "WARN $NAME: unresolved libraries remain:"
    LD_LIBRARY_PATH="$SDK_OUT" ldd "$BIN" | grep 'not found' | sed 's/^/    /'
    missing=1
  fi

  # Per-game flags — REPLICATED FROM play.sh (keep the two in sync when a
  # workaround is added or retired there). pgr3's temporary RenderDoc-capture
  # diagnostics are deliberately NOT replicated: bundles are for playing.
  local FLAGS=""
  case "$NAME" in
    choplifter|ridgeracer)
      FLAGS='--render_target_path_vulkan=fsi'
      ;;
    ridgeracer6)
      FLAGS='--render_target_path_vulkan=fsi --use_fuzzy_alpha_epsilon=true'
      ;;
    splitsecond|raidenfighters)
      FLAGS='--unregistered_function_nonfatal=true'
      ;;
    pgr3)
      FLAGS='--unregistered_function_nonfatal=true --vulkan_allow_present_mode_immediate=false --vulkan_allow_present_mode_mailbox=false --frame_limit=30 --use_fuzzy_alpha_epsilon=true --vulkan_async_skip_incomplete_frames=false'
      ;;
  esac

  # Seed-save auto-install (play.sh parity): only baked in when the game
  # ships one. Copy it into the bundle so the bundle stays self-contained.
  local SEED_SNIPPET=""
  if [ -d "$G/seedsave" ]; then
    cp -rf "$G/seedsave" "$DEST/seedsave"
    SEED_SNIPPET='
# Seed-save auto-install: this title blocks on a missing save; install the
# bundled seed once if the user has none.
for xuiddir in "$HERE"/seedsave/*/; do
  [ -d "$xuiddir" ] || continue
  dest="$HOME/.local/share/'"$NAME"'/$(basename "$xuiddir")"
  if [ ! -d "$dest" ]; then
    mkdir -p "$(dirname "$dest")"
    cp -r "$xuiddir" "$dest"
    echo "installed seed save -> $dest"
  fi
done'
  fi

  cat > "$DEST/launch.sh" <<EOF
#!/usr/bin/env bash
# Standalone launcher for $NAME — generated by tools/make_standalone.sh
# on $(date +%F). Game data is NOT bundled; see README.txt.
set -u
HERE="\$(cd "\$(dirname "\$0")" && pwd)"
cd "\$HERE"

GAME_DATA="$G/extracted"
if [ ! -d "\$GAME_DATA" ]; then
  echo "ERROR: game data not found at \$GAME_DATA"
  echo "This bundle does not include game content; it reads the extracted"
  echo "data from the recomp suite. Re-extract your game there first."
  exit 1
fi

ulimit -c 0
$SEED_SNIPPET
env GDK_BACKEND=x11 LD_LIBRARY_PATH=. \\
  ./$NAME --game_data_root="\$GAME_DATA" --gpu_plugin xenos \\
  --gpu_allow_invalid_fetch_constants=true --audio_maxqframes=64 --license_mask=1 \\
  --headless=true \\
  $FLAGS \\
  "\$@"
status=\$?

# The runtime leaks a ~4.5GB /dev/shm segment if it dies uncleanly; sweep when idle.
pgrep -x "$NAME" >/dev/null 2>&1 || \\
  find /dev/shm -maxdepth 1 -name 'xenia_memory_*' -user "\$(id -un)" -delete 2>/dev/null
exit \$status
EOF
  chmod +x "$DEST/launch.sh"

  cat > "$DEST/README.txt" <<EOF
$NAME — standalone native Linux build (statically recompiled Xbox 360 title)

Run:  ./launch.sh

GAME DATA DEPENDENCY
This bundle contains only the recompiled executable and its support
libraries. The game's own assets are NOT included: launch.sh reads them
from the recomp suite's extracted data directory:

    $G/extracted

If that directory is moved or deleted the game will not start; re-extract
your legally-owned copy of the game there (see the suite's README), or
edit GAME_DATA in launch.sh.

PRIVATE USE ONLY — this bundle embeds recompiled, copyrighted game code.
Do not upload or redistribute it.
EOF

  echo "OK   $NAME -> $DEST  ($(ls "$DEST" | wc -l) files)"
  return $missing
}

rc=0
for name in "$@"; do
  make_bundle "$name" || rc=1
done
exit $rc
